# Reference/prototype configuration file for DNDAI research workspace.
# This file is for planning and documentation only. Do NOT use for deployment.
# Do NOT store real secrets or credentials here.
llama4_model_path: "D:/AI/models/llama4.bin"
stable_diffusion_model_path: "D:/AI/models/stable-diffusion-v1-5"
discord_token: "YOUR_DISCORD_TOKEN"
twitch_token: "YOUR_TWITCH_TOKEN"
campaign_db_path: "e:/Repositories/DNDAI/data/campaigns.db"
log_level: "INFO"
encounter_templates: "e:/Repositories/DNDAI/data/encounter_templates.json"
monster_db_path: "e:/Repositories/DNDAI/data/monsters.json"
npc_templates: "e:/Repositories/DNDAI/data/npc_templates.json"
item_db_path: "e:/Repositories/DNDAI/data/items.json"
artifact_templates: "e:/Repositories/DNDAI/data/artifacts.json"
stat_block_schema: "e:/Repositories/DNDAI/data/stat_block_schema.json"
style_guides: "e:/Repositories/DNDAI/data/style_guides.json"
