# DNDAI config.yaml (Sample)
llama4_model_path: "C:/ai/models/llama4.bin"
stable_diffusion_model_path: "C:/ai/models/stable-diffusion-v1-5"
discord_token: "YOUR_DISCORD_TOKEN"
twitch_token: "YOUR_TWITCH_TOKEN"
campaign_db_path: "data/campaigns.db"
log_level: "INFO"
encounter_templates: "data/encounter_templates.json"
monster_db_path: "data/monsters.json"
npc_templates: "data/npc_templates.json"
item_db_path: "data/items.json"
artifact_templates: "data/artifacts.json"
stat_block_schema: "data/stat_block_schema.json"
style_guides: "data/style_guides.json"
